services:
  payment-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: payment-sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"

  payment-api:
    container_name: payment-gateway-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=payment-db;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - payment-db